import React from "react";
import { Bar } from "react-chartjs-2";
import "./doublearealine.css"; // Assuming this is your CSS file

import {
  Chart as ChartJS,
  BarElement,
  CategoryScale,
  LinearScale,
  Tooltip,
  Legend,
} from "chart.js";

// Register Chart.js components
ChartJS.register(BarElement, CategoryScale, LinearScale, Tooltip, Legend);

const BarChart = () => {
  // Updated dummy data for the bar chart with more variation
  const data = {
    labels: [
      "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct",
      "Nov", "Dec", "Jan", "Feb", "Mar", "Apr"
    ],
    datasets: [
      {
        label: "Balance",
        data: [
          20, -50, 80, -45, 60, -90, 120, -110, 140, -130, 80, -20, 
          -60, 100, -30, 50
        ], // Added more dummy data
        backgroundColor: (context) => {
          const value = context.raw;
          // Color bars based on value
          return value < 0 ? "#fb7d5b" : "#00273a";
        },
        borderColor: "rgba(0, 0, 0, 0.1)",
        borderWidth: 1,
      },
    ],
  };

  const options = {
    responsive: true,
    plugins: {
      legend: {
        display: false, // Disable the legend generated by Chart.js
      },
      tooltip: {
        mode: "index",
        intersect: false,
      },
    },
    scales: {
      x: {
        title: {
          display: true,
          text: "Months", // X-axis title
        },
        grid: {
          display: false, // Remove grid from x-axis
        },
      },
      y: {
        title: {
          display: true,
          text: "Amount", // Y-axis title
        },
        beginAtZero: true,
        grid: {
          drawOnChartArea: true, // Draw grid lines on the chart area
          borderColor: "#ccc", // Light grey border color
          borderWidth: 1,
          lineWidth: 1, // Ensure horizontal lines are visible
          color: "#e0e0e0", // Light grey color for horizontal lines
        },
      },
    },
  };

  return (
    <div>
      {/* Flexbox layout for the header */}
      <div className="header-container">
        <h2 className="linechart-heading">Balance <br /> Analysis</h2>
      </div>
      <div className="graph-chart-container02">
        <Bar data={data} options={options} height={650} width={800} /> {/* Increased height */}
      </div>
    </div>
  );
};

export default BarChart;
