import React from "react";
import { Line } from "react-chartjs-2";
import "./doublearealine.css"; // Assuming this is your CSS file

import {
  Chart as ChartJS,
  LineElement,
  CategoryScale,
  LinearScale,
  PointElement,
  Tooltip,
  Legend,
} from "chart.js";

// Register Chart.js components
ChartJS.register(LineElement, CategoryScale, LinearScale, PointElement, Tooltip, Legend);

const DoubleAreaLineChart = () => {
  // Updated dummy data for the chart with more variation
  const data = {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct"],
    datasets: [
      {
        label: "Sales",
        data: [20, 50, 80, 45, 60, 40, 70, 30, 100, 10], // More varied sales data
        borderColor: "#fb7d5b",
        borderWidth: 4,
        tension: 0.4, // Increased smoothness
        pointRadius: 0, // Remove dots from the line
      },
      {
        label: "Expenses",
        data: [30, 60, 50, 70, 40, 85, 60, 70, 70, 100], // More varied expenses data
        borderColor: "#00273a",
        backgroundColor: "rgba(0, 39, 58, 0.1)",
        borderWidth: 4,
        fill: true, // Makes the chart area under the line filled
        tension: 0.4, // Increased smoothness
        pointRadius: 0, // Remove dots from the line
      },
    ],
  };

  const options = {
    responsive: true,
    plugins: {
      legend: {
        display: false, // Disable the legend generated by Chart.js
      },
      tooltip: {
        mode: "index",
        intersect: false,
      },
    },
    scales: {
      x: {
        title: {
          display: true,
          text: "Months", // X-axis title
        },
        grid: {
          display: false, // Remove grid from x-axis
        },
      },
      y: {
        title: {
          display: true,
          text: "Amount", // Y-axis title
        },
        beginAtZero: true,
        grid: {
          display: false, // Remove grid from y-axis
        },
      },
    },
    maintainAspectRatio: false, // Ensures that the height is independent of the width
    aspectRatio: 2, // Adjust this for your desired aspect ratio
  };

  return (
    <div>
      {/* Flexbox layout for the header */}
      <div className="header-container">
        <h2 className="linechart-heading">Balance <br /> Analysis</h2>
        {/* Custom Legend */}
        <div className="custom-legend">
          <div className="legend-item">
            <span className="legend-circle" style={{ backgroundColor: "#fb7d5b" }}></span>
            Sales
          </div>
          <div className="legend-item">
            <span className="legend-circle" style={{ backgroundColor: "#00273a" }}></span>
            Expenses
          </div>
        </div>
      </div>
      <div className="graph-chart-container">
        <Line data={data} options={options} height={400} width={800} /> {/* Adjust height and width here */}
      </div>
    </div>
  );
};

export default DoubleAreaLineChart;
